In [2]:
# CNN : 성인 남녀 얼굴 이미지 분류 - 이항 분류
import cv2,os,numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [10]:
image_dir='/content/drive/MyDrive/person_img'
xdata,ydata=[],[]

# 남,여 구분 라벨 구하기 - 파일명에서 성별 추출  30_0_0_20170119195539771.jpg - split 함수

for file in os.listdir(image_dir):
    try:
        gender=int(file.split('_')[1])  # 0:male / 1:female
        img_path=os.path.join(image_dir,file)
        img=cv2.imread(img_path)
        img=cv2.resize(img,(64,64))   # 크기 축소
        xdata.append(img)
        ydata.append(gender)
    except:
        continue

print(xdata[0])
print(ydata[0])

xdata=np.array(xdata)/255.0
ydata=np.array(ydata)/255.0

[[[  9  18  15]
  [  4  13  10]
  [  3  12   9]
  ...
  [ 42  64 100]
  [ 26  47  70]
  [161 184 199]]

 [[  7  16  13]
  [  6  15  12]
  [  5  14  11]
  ...
  [ 40  61  90]
  [ 21  41  59]
  [156 178 191]]

 [[  6  19  17]
  [  5  18  16]
  [  4  16  14]
  ...
  [ 20  38  74]
  [ 26  45  72]
  [168 191 212]]

 ...

 [[ 36  29  24]
  [ 31  26  21]
  [ 26  22  21]
  ...
  [  5   1   0]
  [  5   0   1]
  [  5   0   1]]

 [[ 37  28  24]
  [ 31  26  19]
  [ 25  21  20]
  ...
  [  3   1   0]
  [  5   0   1]
  [  5   0   1]]

 [[ 36  27  23]
  [ 31  25  18]
  [ 25  21  20]
  ...
  [  3   1   0]
  [  5   0   1]
  [  5   0   1]]]
1


In [12]:
# train / test
x_train,x_test,y_train,y_test=train_test_split(xdata,ydata,test_size=0.2,random_state=42)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(102, 64, 64, 3) (26, 64, 64, 3) (102,) (26,)


In [15]:
# model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Dropout,Input

model=Sequential([
    Input(shape=(64,64,3)),
    Conv2D(32,(3,3),activation='relu'),
    MaxPooling2D(2,2),
    Conv2D(64,(3,3),activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(128,activation='relu'),
    Dropout(0.3),
    Dense(1,activation='sigmoid'),
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)               │ (None, 62, 62, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 31, 31, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 29, 29, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 14, 14, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 12544)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │     1,605,760 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,625,281 (6.20 MB)

 Trainable params: 1,625,281 (6.20 MB)

 Non-trainable params: 0 (0.00 B)

None
